version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_HOST=mysql
      - DB_USER=whatsapp_user
      - DB_PASSWORD=secure_password
      - DB_NAME=whatsapp_bot_saas
      - JWT_SECRET=your_super_secure_jwt_secret_here
      - JWT_EXPIRES_IN=7d
      - BOT_NAME=WhatsApp Bot SaaS
      - BOT_VERSION=1.0.0
      - MAX_FILE_SIZE=5242880
    depends_on:
      - mysql
    volumes:
      - uploads:/app/uploads
      - auth_sessions:/app/server/auth
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=whatsapp_bot_saas
      - MYSQL_USER=whatsapp_user
      - MYSQL_PASSWORD=secure_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "3306:3306"
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
  uploads:
  auth_sessions: